import {
  Shield,
  BookOpen,
  Waves,
  Store,
  MessageCircle,
  UsersRound,
} from "lucide-react";

// lib/mockdata.ts
import { Testimonial } from "@/types/testimonial";

export const mockTestimonials: Testimonial[] = [
  {
    name: "Emily Carter",
    location: "United States 🇺🇸",
    rating: 5,
    comment: "Amazing tour! Learned so much about Amsterdam’s hidden gems while having fun.",
    date: "Jan 5, 2025",
    avatar: "/avatars/emily.jpg",
    verified: true,
    tourName: "Free Walking Tour Amsterdam"
  },
  {
    name: "Luca Bianchi",
    location: "Italy 🇮🇹",
    rating: 5,
    comment: "Fantastic guide, very engaging and funny. Highly recommended to everyone!",
    date: "Dec 12, 2024",
    avatar: "/avatars/luca.jpg",
    verified: true
  },
  {
    name: "Sophia Müller",
    location: "Germany 🇩🇪",
    rating: 4,
    comment: "Great experience overall! Very informative and well organized.",
    date: "Nov 24, 2024",
    verified: true,
    tourName: "Free Walking Tour Amsterdam"
  },
  {
    name: "James Wilson",
    location: "United Kingdom 🇬🇧",
    rating: 5,
    comment: "One of the best walking tours I’ve attended worldwide!",
    date: "Oct 3, 2024",
    avatar: "/avatars/james.jpg",
    verified: false
  }
];


export const highlights = [
  {
    text: "Stroll through Amsterdam's oldest streets and hidden courtyards",
    icon: BookOpen,
  },
  {
    text: "Walk along UNESCO canals and hear untold stories of the city's Golden Age",
    icon: Waves,
  },
  {
    text: "Learn how WWII shaped Amsterdam's spirit and resilience",
    icon: Shield,
  },
  {
    text: "Step into Chinatown and uncover the city's cultural crossroads",
    icon: Store,
  },
  {
    text: "Get local tips on where to eat, drink, and truly feel like a local",
    icon: MessageCircle,
  },
  {
    text: "Enjoy small, friendly groups led by passionate local guides",
    icon: UsersRound,
  },
];

export const includes = [
  "Complimentary Dutch snack",
  "Professional photos of your group",
  "Local restaurant and bar recommendations",
  "Insider tips for the rest of your stay",
];

export const itinerary = [
  {
    number: 0,
    title: "Meeting Point: Saint Nicholas Basilica",
    description:
      "Look for the guide(s) holding an Orange Umbrella, in front of the Saint Nicholas Church next to Amsterdam Central Station",
  },
  {
    number: 1,
    title: "Damrak – The Birth of the Netherlands",
    description:
      "Discover how Dutch engineering tamed the sea and created an entire nation.",
  },
  {
    number: 2,
    title: "Ons' Lieve Heer op Solder – A Hidden Church",
    description:
      "Learn how a secret church was built in an attic during times of persecution.",
  },
  {
    number: 3,
    title: "Chinatown – East Meets West",
    description:
      "Explore Amsterdam's Chinatown and hear how the Red Light District and Coffeeshop culture shaped modern Dutch society.",
  },
  {
    number: 4,
    title: "The Red Light District – Controversy & Culture",
    description:
      "Walk through the world's most talked-about neighborhood and uncover its complex past.",
  },
  {
    number: 5,
    title: "Nieuwmarkt & De Waag – The Old City Gate",
    description:
      "See the leaning canal houses and find out why they're so narrow.",
  },
  {
    number: 6,
    title: "Oost-Indisch Huis – The Dutch East India Company",
    description:
      "Visit the former headquarters of the world's first multinational and explore Amsterdam's Golden Age legacy.",
  },
  {
    number: 7,
    title: "Jewish Quarter – Courage in Dark Times",
    description:
      "Learn about the Jewish community during WWII and the city's resilience through hardship.",
  },
  {
    number: 8,
    title: "Universiteit van Amsterdam (Oudemanhuispoort)",
    description:
      "Walk through a historic university courtyard surrounded by canals.",
  },
  {
    number: 9,
    title: "Royal Palace & Dam Square – The Grand Finale",
    description:
      "End the tour at the Royal Palace and hear how Amsterdam transformed from a republic into a modern monarchy.",
  },
];

export const faqs = [
  {
    question: "How much does this tour cost?",
    answer:
      "This is a tip based tour. You can book the tour for free. At the end of the tour, you decide what it was worth to you and tip your guide accordingly. Most guests tip 15 to 30 euro per person.",
  },
  {
    question: "Can I tip my guide with card?",
    answer:
      "Yes! Our guides carry card machines. You can choose to tip with card or cash.",
  },
  {
    question: "What if it rains?",
    answer:
      "Tours run rain or shine! We recommend bringing an umbrella or rain jacket. Amsterdam weather can be unpredictable, but our guides make it fun regardless!",
  },
  {
    question: "How do I find the guide?",
    answer:
      "Meet at Saint Nicholas Church (Prins Hendrikkade 73, near Amsterdam Central Station). Look for guides with orange umbrellas. Arrive 10 minutes early.",
  },
  {
    question: "Can I book for a large group?",
    answer:
      "For groups of 6+ people, please contact us directly to arrange a private tour. This ensures the best experience for everyone.",
  },
];

export const COUNTRIES = [
  { id: "af", emoji: "🇦🇫", name: "Afghanistan", code: "+93", phoneLength: { min: 9, max: 9 }, placeholder: "701234567" },
  { id: "al", emoji: "🇦🇱", name: "Albania", code: "+355", phoneLength: { min: 9, max: 9 }, placeholder: "682123456" },
  { id: "dz", emoji: "🇩🇿", name: "Algeria", code: "+213", phoneLength: { min: 9, max: 9 }, placeholder: "551234567" },
  { id: "ad", emoji: "🇦🇩", name: "Andorra", code: "+376", phoneLength: { min: 6, max: 6 }, placeholder: "312345" },
  { id: "ao", emoji: "🇦🇴", name: "Angola", code: "+244", phoneLength: { min: 9, max: 9 }, placeholder: "923456789" },
  { id: "ai", emoji: "🇦🇮", name: "Anguilla", code: "+1-264", phoneLength: { min: 7, max: 7 }, placeholder: "2642351234" },
  { id: "ag", emoji: "🇦🇬", name: "Antigua and Barbuda", code: "+1-268", phoneLength: { min: 7, max: 7 }, placeholder: "2684641234" },
  { id: "ar", emoji: "🇦🇷", name: "Argentina", code: "+54", phoneLength: { min: 10, max: 10 }, placeholder: "1123456789" },
  { id: "am", emoji: "🇦🇲", name: "Armenia", code: "+374", phoneLength: { min: 8, max: 8 }, placeholder: "77123456" },
  { id: "au", emoji: "🇦🇺", name: "Australia", code: "+61", phoneLength: { min: 9, max: 9 }, placeholder: "412345678" },
  { id: "at", emoji: "🇦🇹", name: "Austria", code: "+43", phoneLength: { min: 10, max: 10 }, placeholder: "6601234567" },
  { id: "az", emoji: "🇦🇿", name: "Azerbaijan", code: "+994", phoneLength: { min: 9, max: 9 }, placeholder: "501234567" },
  { id: "bs", emoji: "🇧🇸", name: "Bahamas", code: "+1-242", phoneLength: { min: 7, max: 7 }, placeholder: "2423561234" },
  { id: "bh", emoji: "🇧🇭", name: "Bahrain", code: "+973", phoneLength: { min: 8, max: 8 }, placeholder: "36123456" },
  { id: "bd", emoji: "🇧🇩", name: "Bangladesh", code: "+880", phoneLength: { min: 10, max: 10 }, placeholder: "1712345678" },
  { id: "bb", emoji: "🇧🇧", name: "Barbados", code: "+1-246", phoneLength: { min: 7, max: 7 }, placeholder: "2462501234" },
  { id: "by", emoji: "🇧🇾", name: "Belarus", code: "+375", phoneLength: { min: 9, max: 9 }, placeholder: "291234567" },
  { id: "be", emoji: "🇧🇪", name: "Belgium", code: "+32", phoneLength: { min: 8, max: 9 }, placeholder: "470123456" },
  { id: "bz", emoji: "🇧🇿", name: "Belize", code: "+501", phoneLength: { min: 7, max: 7 }, placeholder: "6121234" },
  { id: "bj", emoji: "🇧🇯", name: "Benin", code: "+229", phoneLength: { min: 8, max: 8 }, placeholder: "90123456" },
  { id: "bt", emoji: "🇧🇹", name: "Bhutan", code: "+975", phoneLength: { min: 8, max: 8 }, placeholder: "17123456" },
  { id: "bo", emoji: "🇧🇴", name: "Bolivia", code: "+591", phoneLength: { min: 8, max: 8 }, placeholder: "71234567" },
  { id: "ba", emoji: "🇧🇦", name: "Bosnia and Herzegovina", code: "+387", phoneLength: { min: 8, max: 8 }, placeholder: "61123456" },
  { id: "bw", emoji: "🇧🇼", name: "Botswana", code: "+267", phoneLength: { min: 7, max: 7 }, placeholder: "71234567" },
  { id: "br", emoji: "🇧🇷", name: "Brazil", code: "+55", phoneLength: { min: 10, max: 11 }, placeholder: "11912345678" },
  { id: "bn", emoji: "🇧🇳", name: "Brunei", code: "+673", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "bg", emoji: "🇧🇬", name: "Bulgaria", code: "+359", phoneLength: { min: 8, max: 8 }, placeholder: "88123456" },
  { id: "bf", emoji: "🇧🇫", name: "Burkina Faso", code: "+226", phoneLength: { min: 8, max: 8 }, placeholder: "70123456" },
  { id: "bi", emoji: "🇧🇮", name: "Burundi", code: "+257", phoneLength: { min: 8, max: 8 }, placeholder: "79123456" },
  { id: "kh", emoji: "🇰🇭", name: "Cambodia", code: "+855", phoneLength: { min: 8, max: 9 }, placeholder: "12345678" },
  { id: "cm", emoji: "🇨🇲", name: "Cameroon", code: "+237", phoneLength: { min: 9, max: 9 }, placeholder: "671234567" },
  { id: "ca", emoji: "🇨🇦", name: "Canada", code: "+1", phoneLength: { min: 10, max: 10 }, placeholder: "6135551234" },
  { id: "cv", emoji: "🇨🇻", name: "Cape Verde", code: "+238", phoneLength: { min: 7, max: 7 }, placeholder: "9123456" },
  { id: "cf", emoji: "🇨🇫", name: "Central African Republic", code: "+236", phoneLength: { min: 8, max: 8 }, placeholder: "70123456" },
  { id: "td", emoji: "🇹🇩", name: "Chad", code: "+235", phoneLength: { min: 8, max: 8 }, placeholder: "66123456" },
  { id: "cl", emoji: "🇨🇱", name: "Chile", code: "+56", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "cn", emoji: "🇨🇳", name: "China", code: "+86", phoneLength: { min: 11, max: 11 }, placeholder: "13912345678" },
  { id: "co", emoji: "🇨🇴", name: "Colombia", code: "+57", phoneLength: { min: 10, max: 10 }, placeholder: "3001234567" },
  { id: "km", emoji: "🇰🇲", name: "Comoros", code: "+269", phoneLength: { min: 7, max: 7 }, placeholder: "3123456" },
  { id: "cg", emoji: "🇨🇬", name: "Congo", code: "+242", phoneLength: { min: 9, max: 9 }, placeholder: "061234567" },
  { id: "cd", emoji: "🇨🇩", name: "DR Congo", code: "+243", phoneLength: { min: 9, max: 9 }, placeholder: "991234567" },
  { id: "cr", emoji: "🇨🇷", name: "Costa Rica", code: "+506", phoneLength: { min: 8, max: 8 }, placeholder: "12345678" },
  { id: "hr", emoji: "🇭🇷", name: "Croatia", code: "+385", phoneLength: { min: 8, max: 9 }, placeholder: "912345678" },
  { id: "cu", emoji: "🇨🇺", name: "Cuba", code: "+53", phoneLength: { min: 8, max: 8 }, placeholder: "52123456" },
  { id: "cy", emoji: "🇨🇾", name: "Cyprus", code: "+357", phoneLength: { min: 8, max: 8 }, placeholder: "96123456" },
  { id: "cz", emoji: "🇨🇿", name: "Czech Republic", code: "+420", phoneLength: { min: 9, max: 9 }, placeholder: "601234567" },
  { id: "dk", emoji: "🇩🇰", name: "Denmark", code: "+45", phoneLength: { min: 8, max: 8 }, placeholder: "12345678" },
  { id: "dj", emoji: "🇩🇯", name: "Djibouti", code: "+253", phoneLength: { min: 8, max: 8 }, placeholder: "77123456" },
  { id: "dm", emoji: "🇩🇲", name: "Dominica", code: "+1-767", phoneLength: { min: 7, max: 7 }, placeholder: "7672751234" },
  { id: "do", emoji: "🇩🇴", name: "Dominican Republic", code: "+1-809", phoneLength: { min: 7, max: 7 }, placeholder: "8092341234" },
  { id: "ec", emoji: "🇪🇨", name: "Ecuador", code: "+593", phoneLength: { min: 9, max: 9 }, placeholder: "991234567" },
  { id: "eg", emoji: "🇪🇬", name: "Egypt", code: "+20", phoneLength: { min: 10, max: 10 }, placeholder: "1012345678" },
  { id: "sv", emoji: "🇸🇻", name: "El Salvador", code: "+503", phoneLength: { min: 8, max: 8 }, placeholder: "70123456" },
  { id: "gq", emoji: "🇬🇶", name: "Equatorial Guinea", code: "+240", phoneLength: { min: 9, max: 9 }, placeholder: "222123456" },
  { id: "er", emoji: "🇪🇷", name: "Eritrea", code: "+291", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "ee", emoji: "🇪🇪", name: "Estonia", code: "+372", phoneLength: { min: 8, max: 8 }, placeholder: "5012345" },
  { id: "et", emoji: "🇪🇹", name: "Ethiopia", code: "+251", phoneLength: { min: 9, max: 9 }, placeholder: "911234567" },
  { id: "fj", emoji: "🇫🇯", name: "Fiji", code: "+679", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "fi", emoji: "🇫🇮", name: "Finland", code: "+358", phoneLength: { min: 8, max: 9 }, placeholder: "401234567" },
  { id: "fr", emoji: "🇫🇷", name: "France", code: "+33", phoneLength: { min: 9, max: 9 }, placeholder: "612345678" },
  { id: "ga", emoji: "🇬🇦", name: "Gabon", code: "+241", phoneLength: { min: 7, max: 7 }, placeholder: "6123456" },
  { id: "gm", emoji: "🇬🇲", name: "Gambia", code: "+220", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "ge", emoji: "🇬🇪", name: "Georgia", code: "+995", phoneLength: { min: 9, max: 9 }, placeholder: "591234567" },
  { id: "de", emoji: "🇩🇪", name: "Germany", code: "+49", phoneLength: { min: 10, max: 11 }, placeholder: "1512345678" },
  { id: "gh", emoji: "🇬🇭", name: "Ghana", code: "+233", phoneLength: { min: 9, max: 9 }, placeholder: "241234567" },
  { id: "gr", emoji: "🇬🇷", name: "Greece", code: "+30", phoneLength: { min: 10, max: 10 }, placeholder: "6912345678" },
  { id: "gd", emoji: "🇬🇩", name: "Grenada", code: "+1-473", phoneLength: { min: 7, max: 7 }, placeholder: "4734031234" },
  { id: "gt", emoji: "🇬🇹", name: "Guatemala", code: "+502", phoneLength: { min: 8, max: 8 }, placeholder: "12345678" },
  { id: "gn", emoji: "🇬🇳", name: "Guinea", code: "+224", phoneLength: { min: 9, max: 9 }, placeholder: "621234567" },
  { id: "gw", emoji: "🇬🇼", name: "Guinea-Bissau", code: "+245", phoneLength: { min: 7, max: 7 }, placeholder: "9123456" },
  { id: "gy", emoji: "🇬🇾", name: "Guyana", code: "+592", phoneLength: { min: 7, max: 7 }, placeholder: "6123456" },
  { id: "ht", emoji: "🇭🇹", name: "Haiti", code: "+509", phoneLength: { min: 8, max: 8 }, placeholder: "34123456" },
  { id: "hn", emoji: "🇭🇳", name: "Honduras", code: "+504", phoneLength: { min: 8, max: 8 }, placeholder: "12345678" },
  { id: "hk", emoji: "🇭🇰", name: "Hong Kong", code: "+852", phoneLength: { min: 8, max: 8 }, placeholder: "12345678" },
  { id: "hu", emoji: "🇭🇺", name: "Hungary", code: "+36", phoneLength: { min: 9, max: 9 }, placeholder: "201234567" },
  { id: "is", emoji: "🇮🇸", name: "Iceland", code: "+354", phoneLength: { min: 7, max: 7 }, placeholder: "6123456" },
  { id: "in", emoji: "🇮🇳", name: "India", code: "+91", phoneLength: { min: 10, max: 10 }, placeholder: "9812345678" },
  { id: "id", emoji: "🇮🇩", name: "Indonesia", code: "+62", phoneLength: { min: 9, max: 10 }, placeholder: "81234567890" },
  { id: "ir", emoji: "🇮🇷", name: "Iran", code: "+98", phoneLength: { min: 10, max: 10 }, placeholder: "9121234567" },
  { id: "iq", emoji: "🇮🇶", name: "Iraq", code: "+964", phoneLength: { min: 10, max: 10 }, placeholder: "7901234567" },
  { id: "ie", emoji: "🇮🇪", name: "Ireland", code: "+353", phoneLength: { min: 9, max: 9 }, placeholder: "851234567" },
  { id: "il", emoji: "🇮🇱", name: "Israel", code: "+972", phoneLength: { min: 8, max: 8 }, placeholder: "50123456" },
  { id: "it", emoji: "🇮🇹", name: "Italy", code: "+39", phoneLength: { min: 9, max: 10 }, placeholder: "3123456789" },
  { id: "jm", emoji: "🇯🇲", name: "Jamaica", code: "+1-876", phoneLength: { min: 7, max: 7 }, placeholder: "8763121234" },
  { id: "jp", emoji: "🇯🇵", name: "Japan", code: "+81", phoneLength: { min: 10, max: 10 }, placeholder: "9012345678" },
  { id: "jo", emoji: "🇯🇴", name: "Jordan", code: "+962", phoneLength: { min: 8, max: 9 }, placeholder: "791234567" },
  { id: "kz", emoji: "🇰🇿", name: "Kazakhstan", code: "+7", phoneLength: { min: 10, max: 10 }, placeholder: "7012345678" },
  { id: "ke", emoji: "🇰🇪", name: "Kenya", code: "+254", phoneLength: { min: 9, max: 9 }, placeholder: "712345678" },
  { id: "ki", emoji: "🇰🇮", name: "Kiribati", code: "+686", phoneLength: { min: 5, max: 5 }, placeholder: "12345" },
  { id: "kw", emoji: "🇰🇼", name: "Kuwait", code: "+965", phoneLength: { min: 8, max: 8 }, placeholder: "50123456" },
  { id: "kg", emoji: "🇰🇬", name: "Kyrgyzstan", code: "+996", phoneLength: { min: 9, max: 9 }, placeholder: "700123456" },
  { id: "la", emoji: "🇱🇦", name: "Laos", code: "+856", phoneLength: { min: 8, max: 8 }, placeholder: "20123456" },
  { id: "lv", emoji: "🇱🇻", name: "Latvia", code: "+371", phoneLength: { min: 8, max: 8 }, placeholder: "20123456" },
  { id: "lb", emoji: "🇱🇧", name: "Lebanon", code: "+961", phoneLength: { min: 7, max: 8 }, placeholder: "3123456" },
  { id: "ls", emoji: "🇱🇸", name: "Lesotho", code: "+266", phoneLength: { min: 8, max: 8 }, placeholder: "50123456" },
  { id: "lr", emoji: "🇱🇷", name: "Liberia", code: "+231", phoneLength: { min: 8, max: 8 }, placeholder: "77123456" },
  { id: "ly", emoji: "🇱🇾", name: "Libya", code: "+218", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "li", emoji: "🇱🇮", name: "Liechtenstein", code: "+423", phoneLength: { min: 7, max: 7 }, placeholder: "6123456" },
  { id: "lt", emoji: "🇱🇹", name: "Lithuania", code: "+370", phoneLength: { min: 8, max: 8 }, placeholder: "60123456" },
  { id: "lu", emoji: "🇱🇺", name: "Luxembourg", code: "+352", phoneLength: { min: 9, max: 9 }, placeholder: "621234567" },
  { id: "mo", emoji: "🇲🇴", name: "Macao", code: "+853", phoneLength: { min: 8, max: 8 }, placeholder: "66123456" },
  { id: "mg", emoji: "🇲🇬", name: "Madagascar", code: "+261", phoneLength: { min: 9, max: 9 }, placeholder: "321234567" },
  { id: "mw", emoji: "🇲🇼", name: "Malawi", code: "+265", phoneLength: { min: 9, max: 9 }, placeholder: "991234567" },
  { id: "my", emoji: "🇲🇾", name: "Malaysia", code: "+60", phoneLength: { min: 9, max: 10 }, placeholder: "123456789" },
  { id: "mv", emoji: "🇲🇻", name: "Maldives", code: "+960", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "ml", emoji: "🇲🇱", name: "Mali", code: "+223", phoneLength: { min: 8, max: 8 }, placeholder: "70123456" },
  { id: "mt", emoji: "🇲🇹", name: "Malta", code: "+356", phoneLength: { min: 8, max: 8 }, placeholder: "99123456" },
  { id: "mh", emoji: "🇲🇭", name: "Marshall Islands", code: "+692", phoneLength: { min: 7, max: 7 }, placeholder: "2351234" },
  { id: "mr", emoji: "🇲🇷", name: "Mauritania", code: "+222", phoneLength: { min: 8, max: 8 }, placeholder: "22123456" },
  { id: "mu", emoji: "🇲🇺", name: "Mauritius", code: "+230", phoneLength: { min: 8, max: 8 }, placeholder: "52123456" },
  { id: "mx", emoji: "🇲🇽", name: "Mexico", code: "+52", phoneLength: { min: 10, max: 10 }, placeholder: "5512345678" },
  { id: "fm", emoji: "🇫🇲", name: "Micronesia", code: "+691", phoneLength: { min: 7, max: 7 }, placeholder: "3201234" },
  { id: "md", emoji: "🇲🇩", name: "Moldova", code: "+373", phoneLength: { min: 8, max: 8 }, placeholder: "69123456" },
  { id: "mc", emoji: "🇲🇨", name: "Monaco", code: "+377", phoneLength: { min: 8, max: 8 }, placeholder: "93123456" },
  { id: "mn", emoji: "🇲🇳", name: "Mongolia", code: "+976", phoneLength: { min: 8, max: 8 }, placeholder: "88123456" },
  { id: "me", emoji: "🇲🇪", name: "Montenegro", code: "+382", phoneLength: { min: 8, max: 8 }, placeholder: "67123456" },
  { id: "ma", emoji: "🇲🇦", name: "Morocco", code: "+212", phoneLength: { min: 9, max: 9 }, placeholder: "612345678" },
  { id: "mz", emoji: "🇲🇿", name: "Mozambique", code: "+258", phoneLength: { min: 9, max: 9 }, placeholder: "821234567" },
  { id: "mm", emoji: "🇲🇲", name: "Myanmar", code: "+95", phoneLength: { min: 8, max: 9 }, placeholder: "9123456789" },
  { id: "na", emoji: "🇳🇦", name: "Namibia", code: "+264", phoneLength: { min: 9, max: 9 }, placeholder: "811234567" },
  { id: "nr", emoji: "🇳🇷", name: "Nauru", code: "+674", phoneLength: { min: 7, max: 7 }, placeholder: "5551234" },
  { id: "np", emoji: "🇳🇵", name: "Nepal", code: "+977", phoneLength: { min: 8, max: 9 }, placeholder: "9812345678" },
  { id: "nl", emoji: "🇳🇱", name: "Netherlands", code: "+31", phoneLength: { min: 9, max: 9 }, placeholder: "612345678" },
  { id: "nz", emoji: "🇳🇿", name: "New Zealand", code: "+64", phoneLength: { min: 8, max: 9 }, placeholder: "211234567" },
  { id: "ni", emoji: "🇳🇮", name: "Nicaragua", code: "+505", phoneLength: { min: 8, max: 8 }, placeholder: "81234567" },
  { id: "ne", emoji: "🇳🇪", name: "Niger", code: "+227", phoneLength: { min: 8, max: 8 }, placeholder: "96123456" },
  { id: "ng", emoji: "🇳🇬", name: "Nigeria", code: "+234", phoneLength: { min: 10, max: 10 }, placeholder: "8012345678" },
  { id: "kp", emoji: "🇰🇵", name: "North Korea", code: "+850", phoneLength: { min: 9, max: 9 }, placeholder: "2123456789" },
  { id: "mk", emoji: "🇲🇰", name: "North Macedonia", code: "+389", phoneLength: { min: 8, max: 8 }, placeholder: "70123456" },
  { id: "no", emoji: "🇳🇴", name: "Norway", code: "+47", phoneLength: { min: 8, max: 8 }, placeholder: "12345678" },
  { id: "om", emoji: "🇴🇲", name: "Oman", code: "+968", phoneLength: { min: 8, max: 8 }, placeholder: "92123456" },
  { id: "pk", emoji: "🇵🇰", name: "Pakistan", code: "+92", phoneLength: { min: 10, max: 10 }, placeholder: "3001234567" },
  { id: "pw", emoji: "🇵🇼", name: "Palau", code: "+680", phoneLength: { min: 7, max: 7 }, placeholder: "6201234" },
  { id: "ps", emoji: "🇵🇸", name: "Palestine", code: "+970", phoneLength: { min: 9, max: 9 }, placeholder: "591234567" },
  { id: "pa", emoji: "🇵🇦", name: "Panama", code: "+507", phoneLength: { min: 8, max: 8 }, placeholder: "61234567" },
  { id: "pg", emoji: "🇵🇬", name: "Papua New Guinea", code: "+675", phoneLength: { min: 8, max: 8 }, placeholder: "70123456" },
  { id: "py", emoji: "🇵🇾", name: "Paraguay", code: "+595", phoneLength: { min: 9, max: 9 }, placeholder: "981234567" },
  { id: "pe", emoji: "🇵🇪", name: "Peru", code: "+51", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "ph", emoji: "🇵🇭", name: "Philippines", code: "+63", phoneLength: { min: 10, max: 10 }, placeholder: "9171234567" },
  { id: "pl", emoji: "🇵🇱", name: "Poland", code: "+48", phoneLength: { min: 9, max: 9 }, placeholder: "501234567" },
  { id: "pt", emoji: "🇵🇹", name: "Portugal", code: "+351", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "qa", emoji: "🇶🇦", name: "Qatar", code: "+974", phoneLength: { min: 8, max: 8 }, placeholder: "33123456" },
  { id: "ro", emoji: "🇷🇴", name: "Romania", code: "+40", phoneLength: { min: 9, max: 9 }, placeholder: "721234567" },
  { id: "ru", emoji: "🇷🇺", name: "Russia", code: "+7", phoneLength: { min: 10, max: 10 }, placeholder: "9161234567" },
  { id: "rw", emoji: "🇷🇼", name: "Rwanda", code: "+250", phoneLength: { min: 9, max: 9 }, placeholder: "781234567" },
  { id: "kn", emoji: "🇰🇳", name: "Saint Kitts and Nevis", code: "+1-869", phoneLength: { min: 7, max: 7 }, placeholder: "8697651234" },
  { id: "lc", emoji: "🇱🇨", name: "Saint Lucia", code: "+1-758", phoneLength: { min: 7, max: 7 }, placeholder: "7584841234" },
  { id: "vc", emoji: "🇻🇨", name: "Saint Vincent", code: "+1-784", phoneLength: { min: 7, max: 7 }, placeholder: "7844301234" },
  { id: "ws", emoji: "🇼🇸", name: "Samoa", code: "+685", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "sm", emoji: "🇸🇲", name: "San Marino", code: "+378", phoneLength: { min: 6, max: 6 }, placeholder: "661234" },
  { id: "st", emoji: "🇸🇹", name: "São Tomé and Príncipe", code: "+239", phoneLength: { min: 7, max: 7 }, placeholder: "9123456" },
  { id: "sa", emoji: "🇸🇦", name: "Saudi Arabia", code: "+966", phoneLength: { min: 9, max: 9 }, placeholder: "501234567" },
  { id: "sn", emoji: "🇸🇳", name: "Senegal", code: "+221", phoneLength: { min: 9, max: 9 }, placeholder: "771234567" },
  { id: "rs", emoji: "🇷🇸", name: "Serbia", code: "+381", phoneLength: { min: 8, max: 9 }, placeholder: "641234567" },
  { id: "sc", emoji: "🇸🇨", name: "Seychelles", code: "+248", phoneLength: { min: 7, max: 7 }, placeholder: "2512345" },
  { id: "sl", emoji: "🇸🇱", name: "Sierra Leone", code: "+232", phoneLength: { min: 8, max: 8 }, placeholder: "76123456" },
  { id: "sg", emoji: "🇸🇬", name: "Singapore", code: "+65", phoneLength: { min: 8, max: 8 }, placeholder: "81234567" },
  { id: "sk", emoji: "🇸🇰", name: "Slovakia", code: "+421", phoneLength: { min: 9, max: 9 }, placeholder: "901234567" },
  { id: "si", emoji: "🇸🇮", name: "Slovenia", code: "+386", phoneLength: { min: 8, max: 8 }, placeholder: "31234567" },
  { id: "sb", emoji: "🇸🇧", name: "Solomon Islands", code: "+677", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "so", emoji: "🇸🇴", name: "Somalia", code: "+252", phoneLength: { min: 9, max: 9 }, placeholder: "907123456" },
  { id: "za", emoji: "🇿🇦", name: "South Africa", code: "+27", phoneLength: { min: 9, max: 9 }, placeholder: "821234567" },
  { id: "kr", emoji: "🇰🇷", name: "South Korea", code: "+82", phoneLength: { min: 9, max: 10 }, placeholder: "1012345678" },
  { id: "ss", emoji: "🇸🇸", name: "South Sudan", code: "+211", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "es", emoji: "🇪🇸", name: "Spain", code: "+34", phoneLength: { min: 9, max: 9 }, placeholder: "612345678" },
  { id: "lk", emoji: "🇱🇰", name: "Sri Lanka", code: "+94", phoneLength: { min: 9, max: 9 }, placeholder: "771234567" },
  { id: "sd", emoji: "🇸🇩", name: "Sudan", code: "+249", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "sr", emoji: "🇸🇷", name: "Suriname", code: "+597", phoneLength: { min: 7, max: 7 }, placeholder: "8123456" },
  { id: "sz", emoji: "🇸🇿", name: "Eswatini", code: "+268", phoneLength: { min: 8, max: 8 }, placeholder: "76123456" },
  { id: "se", emoji: "🇸🇪", name: "Sweden", code: "+46", phoneLength: { min: 7, max: 9 }, placeholder: "701234567" },
  { id: "ch", emoji: "🇨🇭", name: "Switzerland", code: "+41", phoneLength: { min: 9, max: 9 }, placeholder: "791234567" },
  { id: "sy", emoji: "🇸🇾", name: "Syria", code: "+963", phoneLength: { min: 9, max: 9 }, placeholder: "991234567" },
  { id: "tw", emoji: "🇹🇼", name: "Taiwan", code: "+886", phoneLength: { min: 9, max: 9 }, placeholder: "912345678" },
  { id: "tj", emoji: "🇹🇯", name: "Tajikistan", code: "+992", phoneLength: { min: 9, max: 9 }, placeholder: "901234567" },
  { id: "tz", emoji: "🇹🇿", name: "Tanzania", code: "+255", phoneLength: { min: 9, max: 9 }, placeholder: "712345678" },
  { id: "th", emoji: "🇹🇭", name: "Thailand", code: "+66", phoneLength: { min: 8, max: 9 }, placeholder: "812345678" },
  { id: "tl", emoji: "🇹🇱", name: "Timor-Leste", code: "+670", phoneLength: { min: 7, max: 7 }, placeholder: "7123456" },
  { id: "tg", emoji: "🇹🇬", name: "Togo", code: "+228", phoneLength: { min: 8, max: 8 }, placeholder: "90123456" },
  { id: "to", emoji: "🇹🇴", name: "Tonga", code: "+676", phoneLength: { min: 5, max: 5 }, placeholder: "12345" },
  { id: "tt", emoji: "🇹🇹", name: "Trinidad and Tobago", code: "+1-868", phoneLength: { min: 7, max: 7 }, placeholder: "8686251234" },
  { id: "tn", emoji: "🇹🇳", name: "Tunisia", code: "+216", phoneLength: { min: 8, max: 8 }, placeholder: "20123456" },
  { id: "tr", emoji: "🇹🇷", name: "Turkey", code: "+90", phoneLength: { min: 10, max: 10 }, placeholder: "5321234567" },
  { id: "tm", emoji: "🇹🇲", name: "Turkmenistan", code: "+993", phoneLength: { min: 8, max: 8 }, placeholder: "65123456" },
  { id: "tc", emoji: "🇹🇨", name: "Turks and Caicos", code: "+1-649", phoneLength: { min: 7, max: 7 }, placeholder: "6492311234" },
  { id: "tv", emoji: "🇹🇻", name: "Tuvalu", code: "+688", phoneLength: { min: 5, max: 5 }, placeholder: "20123" },
  { id: "ug", emoji: "🇺🇬", name: "Uganda", code: "+256", phoneLength: { min: 9, max: 9 }, placeholder: "712345678" },
  { id: "ua", emoji: "🇺🇦", name: "Ukraine", code: "+380", phoneLength: { min: 9, max: 9 }, placeholder: "501234567" },
  { id: "ae", emoji: "🇦🇪", name: "United Arab Emirates", code: "+971", phoneLength: { min: 9, max: 9 }, placeholder: "501234567" },
  { id: "gb", emoji: "🇬🇧", name: "United Kingdom", code: "+44", phoneLength: { min: 10, max: 10 }, placeholder: "7912345678" },
  { id: "us", emoji: "🇺🇸", name: "United States", code: "+1", phoneLength: { min: 10, max: 10 }, placeholder: "2025551234" },
  { id: "uy", emoji: "🇺🇾", name: "Uruguay", code: "+598", phoneLength: { min: 8, max: 9 }, placeholder: "91234567" },
  { id: "uz", emoji: "🇺🇿", name: "Uzbekistan", code: "+998", phoneLength: { min: 9, max: 9 }, placeholder: "901234567" },
  { id: "vu", emoji: "🇻🇺", name: "Vanuatu", code: "+678", phoneLength: { min: 7, max: 7 }, placeholder: "5123456" },
  { id: "va", emoji: "🇻🇦", name: "Vatican City", code: "+379", phoneLength: { min: 6, max: 6 }, placeholder: "661234" },
  { id: "ve", emoji: "🇻🇪", name: "Venezuela", code: "+58", phoneLength: { min: 10, max: 10 }, placeholder: "4121234567" },
  { id: "vn", emoji: "🇻🇳", name: "Vietnam", code: "+84", phoneLength: { min: 9, max: 10 }, placeholder: "912345678" },
  { id: "ye", emoji: "🇾🇪", name: "Yemen", code: "+967", phoneLength: { min: 9, max: 9 }, placeholder: "712345678" },
  { id: "zm", emoji: "🇿🇲", name: "Zambia", code: "+260", phoneLength: { min: 9, max: 9 }, placeholder: "971234567" },
  { id: "zw", emoji: "🇿🇼", name: "Zimbabwe", code: "+263", phoneLength: { min: 9, max: 9 }, placeholder: "712345678" },
];